name: Prettier Backend

on:
  push:
    branches: [ "*" ]

jobs:
  prettier:
    name: Run Prettier backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Pretter
        run: npm run prettier:fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
          commit_user_name: GitHub Actions
